### ISSUE TITLE
WARNING: Sun elevation will not reach -12.000000 again until 2020-07-28

### ISSUE THREAD

**Issue by palengh** [pnbruckner/ha-sun2#18]
Thank you for a nice add-on to HA, @pnbruckner.
I would not call this an error, nor would I expect a WARNING for the fact the sun will not be lower than -12 or -18 in the summer months.

I live in the Oslo region, at 59 degrees North.
We love the long summer nights up here :-)
`
2020-05-24 22:50:20 WARNING (MainThread) [custom_components.sun2.binary_sensor] Sun elevation will not reach -12.000000 again until 2020-07-28
2020-05-24 22:50:20 WARNING (MainThread) [custom_components.sun2.binary_sensor] Sun elevation will not reach -18.000000 again until 2020-08-18
`

**Comment by pnbruckner** [comment]
It's only a warning because some people may have automations, etc. that use the binary sensor to make something happen and expect it to do so daily. The warning should only happen once when the sensor updates and notices that the next update will happen more than 24 hours in the future. And, of course, it will also happen once at startup if HA is restarted.

Do you really see this as a problem?

**Comment by palengh** [comment]
Not A problem at all. 
I was just surprised to receive the notice in the log because it’s normal around here to have long days in the summer. 

I assume the same info is presented the other way around; when the sun is not reaching altitude, eg. 6 degrees until  February x, which is equally common at these latitudes.

**Comment by Moonbase59** [comment]
That’s actually nice (and good that you calculate taking the polar regions into account). Remember it was quite some calculations (and returning 'None' values) when I built my astronomy stuff back in the days.
