### ISSUE TITLE
Enhancement to add blue hour and golden hour events

### ISSUE THREAD

**Issue by kaizersoje** [pnbruckner/ha-sun2#19]
Could you add point in time sensors for blue hour and golden hour times as shown in the image below?

![twilights-magic-hours](https://user-images.githubusercontent.com/54566217/82960711-96478300-9ffe-11ea-99b6-5dda45ed39f9.jpg)

These are events captured in the Astral package.

**Comment by palengh** [comment]
I have extended my Binary sensors for just that purpose. Just add the elevation and give it a name in your config file.

**Comment by pnbruckner** [comment]
@kaizersoje I'm not sure what you're asking for. Per the picture, "Golden Hour" and "Blue Hour" are not points in time but periods of time. Are you asking for new point in time sensors that correspond to -4 and +6 degrees, for both rising and setting? What should they be called? blue_dawn, golden_dawn, golden_dusk & blue_dusk? Please be very specific.

**Comment by kaizersoje** [comment]
Well, the picture has the different "dawn" and "dusk" as periods too. However, in the code, they are set up as points in time sensors. I was asking it to be set in a similar manner.
For the names, it can be called be as <blue/golden>_hour_<dawn/dusk>. Does this make sense?

**Comment by palengh** [comment]
The Blue Hour phenomenon is not only related to sun elevation.  In fact, the blue hour occurs when the Sun is far enough below the horizon so that the sunlight's blue wavelengths dominate. 
The Blue hour will vary from south to north. Eg. here in Norway we experience long periods of Blue hours in the winter because the long period of the sun setting/rising.

This website was useful to determine the effect at various locations
[https://jekophoto.eu/tools/twilight-calculator-blue-hour-golden-hour/index.php](url)

 The effect of the bluish light also varies due to clouds, and is most effective when the sky is clear.
Time of year, location, and air quality all have an impact on the exact timing of blue hour
[https://en.wikipedia.org/wiki/Blue_hour](url)

**Comment by pnbruckner** [comment]
@kaizersoje I know it's been a long time since you opened this issue, and you may not care anymore. But, FWIW, dawn & dusk are not periods, they are indeed points in time.

Anyway, although it may not be exactly what you were looking for, one option would be as suggested above. Create a binary sensor giving the angle you care about. When it goes `'off'` -> `'on'`, then the point in time in the morning has been reached, and when it goes `'on'` -> `'off'`, then the point in time in the evening has been reached. If you only cared when these events happened (say, for triggering an automation), that should suffice.

Another possibility might be the new phase sensor. This has attributes for when the time is in either the so-called blue or golden hours. There's also an attribute that indicates if the sun is rising or falling. Maybe those, either directly, or through a template sensor, could get you what you want.

I'll leave this open for a bit to give you a chance to comment, again if you care anymore.

**Comment by kaizersoje** [comment]
Hi @pnbruckner, thanks for taking the time to send to post your thoughts. I did see that the `sun_phase` sensor has the `golden_hour` and `blue_hour` attributes. Let me go through your comment in more detail and I well get back to you.

**Comment by SVH-Powel** [comment]
I need the times for these events so that I can plan some outdoor activities. I have solved it with some templating. It is showing the times for the previous day, but that is OK for me. I was wondering about creating a fork of this integration and modify it, but ended up with these template sensors instead. Maybe they are useful for others....

template:
  - trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      above: -6.0
    sensor:
    - name: "Blue hour starting in the morning"
      state: "{{ states('sensor.time') }}"
  - trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: -6.0
    sensor:
    - name: "Blue hour ends in the evening"
      state: "{{ states('sensor.time') }}"
  - trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      above: -4.0
    sensor:
    - name: "Golden hour starting in the morning"
      state: "{{ states('sensor.time') }}"
  - trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      above: 6.0
    sensor:
    - name: "Golden hour ends in the morning"
      state: "{{ states('sensor.time') }}"
  - trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: 6.0
    sensor:
    - name: "Golden hour starting in the evening"
      state: "{{ states('sensor.time') }}"
  - trigger:
    - platform: numeric_state
      entity_id: sun.sun
      attribute: elevation
      below: -4.0
    sensor:
    - name: "Golden hour ends in the evening"
      state: "{{ states('sensor.time') }}"
